package codingTest.자료구조.stack;

import codingTest.자료구조.stack.nodeStack.day1.NodeStack;
import codingTest.자료구조.stack.nodeStack.day10.NodeStack10;
import codingTest.자료구조.stack.nodeStack.day11.NodeStack11;
import codingTest.자료구조.stack.nodeStack.day12.NodeStack12;
import codingTest.자료구조.stack.nodeStack.day13.NodeStack13;
import codingTest.자료구조.stack.nodeStack.day14.NodeStack14;
import codingTest.자료구조.stack.nodeStack.day15.NodeStack15;
import codingTest.자료구조.stack.nodeStack.day16.NodeStack16;
import codingTest.자료구조.stack.nodeStack.day17.NodeStack17;
import codingTest.자료구조.stack.nodeStack.day18.NodeStack18;
import codingTest.자료구조.stack.nodeStack.day19.NodeStack19;
import codingTest.자료구조.stack.nodeStack.day2.NodeStack2;
import codingTest.자료구조.stack.nodeStack.day20.NodeStack20;
import codingTest.자료구조.stack.nodeStack.day21.NodeStack21;
import codingTest.자료구조.stack.nodeStack.day22.NodeStack22;
import codingTest.자료구조.stack.nodeStack.day23.NodeStack23;
import codingTest.자료구조.stack.nodeStack.day24.NodeStack24;
import codingTest.자료구조.stack.nodeStack.day25.NodeStack25;
import codingTest.자료구조.stack.nodeStack.day3.NodeStack4;
import codingTest.자료구조.stack.nodeStack.day5.NodeStack5;
import codingTest.자료구조.stack.nodeStack.day6.NodeStack6;
import codingTest.자료구조.stack.nodeStack.day7.NodeStack7;
import codingTest.자료구조.stack.nodeStack.day8.NodeStack8;
import codingTest.자료구조.stack.nodeStack.day9.NodeStack9;

public class NodeStackMain {

	public static void main(String[] args) {
		System.out.println("-----nodeStack1");
		NodeStack<Integer> nodeStack = new NodeStack<>();
		nodeStack.push(1);
		nodeStack.push(2);
		nodeStack.push(3);
		nodeStack.push(4);
		nodeStack.push(5);
		nodeStack.printStack();
		
		System.out.println("-----nodeStack2");
		NodeStack2<Integer> nodeStack2 = new NodeStack2<Integer>();
		nodeStack2.push(1);
		nodeStack2.push(2);
		nodeStack2.push(4);
		nodeStack2.push(5);
		nodeStack2.push(3);
		nodeStack2.printStack();
		nodeStack2.pop();
		nodeStack2.pop();
		nodeStack2.printStack();
		System.out.println(nodeStack2.isEmpty());
		nodeStack2.clear();
		System.out.println(nodeStack2.isEmpty());
		
		System.out.println("-----nodeStack3");
		NodeStack4<Integer> nodeStack3 = new NodeStack4<Integer>();
		nodeStack3.push(1);
		nodeStack3.push(2);
		nodeStack3.push(4);
		nodeStack3.push(5);
		nodeStack3.push(3);
		nodeStack3.printStack();
		System.out.println(nodeStack3.pop());
		System.out.println(nodeStack3.pop());
		System.out.println(nodeStack3.pop());
		System.out.println(nodeStack3.pop());
		//nodeStack3.clear();
		System.out.println(nodeStack3.isEmpty());
		nodeStack3.printStack();
		
		System.out.println("-----nodeStack4");
		NodeStack4<Integer> nodeStack4 = new NodeStack4<Integer>();
		nodeStack4.push(1);
		nodeStack4.push(2);
		nodeStack4.push(4);
		nodeStack4.push(5);
		nodeStack4.push(3);
		nodeStack4.printStack();
		nodeStack4.clear();
//		System.out.println(nodeStack4.pop());
//		System.out.println(nodeStack4.pop());
//		System.out.println(nodeStack4.pop());
//		System.out.println(nodeStack4.pop());
		System.out.println(nodeStack4.isEmpty());
		nodeStack4.printStack();
//		
		System.out.println("-----nodeStack5");
		NodeStack5<Integer> nodeStack5 = new NodeStack5<Integer>();
		nodeStack5.push(1);
		nodeStack5.push(2);
		nodeStack5.push(4);
		nodeStack5.push(5);
		nodeStack5.push(3);
		nodeStack5.printStack();
		nodeStack5.pop();
		nodeStack5.pop();
		nodeStack5.printStack();
		nodeStack5.clear();
		System.out.println(nodeStack5.isEmpty());
		nodeStack5.printStack();
//		
		System.out.println("-----nodeStack6");
		NodeStack6<Integer> nodeStack6 = new NodeStack6<Integer>();
		nodeStack6.push(1);
		nodeStack6.push(2);
		nodeStack6.push(4);
		nodeStack6.push(5);
		nodeStack6.push(3);
		nodeStack6.printStack();
		nodeStack6.pop();
		nodeStack6.pop();
		nodeStack6.printStack();
		nodeStack6.clear();
		System.out.println(nodeStack6.isEmpty());
		nodeStack6.printStack();
		
		System.out.println("-----nodeStack7");
		NodeStack7<Integer> nodeStack7 = new NodeStack7<Integer>();
		nodeStack7.push(1);
		nodeStack7.push(2);
		nodeStack7.push(4);
		nodeStack7.push(5);
		nodeStack7.push(3); 
		nodeStack7.printStack();
		nodeStack7.pop();
		nodeStack7.pop();
		nodeStack7.printStack();
		nodeStack7.clear();
		System.out.println(nodeStack7.isEmpty());
		nodeStack7.printStack();
		
		System.out.println("-----nodeStack8");
		NodeStack8<Integer> nodeStack8 = new NodeStack8<Integer>();
		nodeStack8.push(1);
		nodeStack8.push(2);
		nodeStack8.push(4);
		nodeStack8.push(5);
		nodeStack8.push(3); 
		nodeStack8.printStack();
		nodeStack8.pop();
		nodeStack8.pop();
		nodeStack8.printStack();
		nodeStack8.clear();
		System.out.println(nodeStack8.isEmpty());
		nodeStack8.printStack();
		
		
		System.out.println("-----nodeStack9");
		NodeStack9<Integer> nodeStack9 = new NodeStack9<Integer>();
		nodeStack9.push(1);
		nodeStack9.push(2);
		nodeStack9.push(4);
		nodeStack9.push(5);
		nodeStack9.push(3); 
		nodeStack9.printStack();
		nodeStack9.pop();
		nodeStack9.pop();
		nodeStack9.pop();
		nodeStack9.pop();
		nodeStack9.pop();
		//nodeStack9.printStack();
		nodeStack9.clear();
		System.out.println(nodeStack9.isEmpty());
		//nodeStack9.printStack();
		
		System.out.println("-----nodeStack10");
		NodeStack10<Integer> nodeStack10 = new NodeStack10<Integer>();
		nodeStack10.push(1);
		nodeStack10.peek();
		nodeStack10.push(2);
		nodeStack10.push(4);
		nodeStack10.push(5);
		nodeStack10.push(3); 
		nodeStack10.printStack();
		nodeStack10.pop();
		nodeStack10.pop();
		nodeStack10.printStack();
		nodeStack10.pop();
		nodeStack10.pop();
		nodeStack10.printStack();
		nodeStack10.pop();
		//nodeStack10.clear();
		System.out.println(nodeStack10.isEmpty());
		
		System.out.println("-----nodeStack11");
		NodeStack11<Integer> nodeStack11 = new NodeStack11<Integer>();
		nodeStack11.push(1);
		nodeStack11.peek();
		nodeStack11.push(2);
		nodeStack11.push(4);
		nodeStack11.push(5);
		nodeStack11.push(3); 
		nodeStack11.printStack();
		nodeStack11.pop();
		nodeStack11.pop();
		nodeStack11.printStack();
		nodeStack11.pop();
		nodeStack11.pop();
		nodeStack11.printStack();
		nodeStack11.pop();
		//nodeStack10.clear();
		System.out.println(nodeStack11.isEmpty());
		
		System.out.println("-----nodeStack12");
		NodeStack12<Integer> nodeStack12 = new NodeStack12<Integer>();
		nodeStack12.push(1);
		nodeStack12.peek();
		nodeStack12.push(2);
		nodeStack12.push(4);
		nodeStack12.push(5);
		nodeStack12.push(3); 
		nodeStack12.printStack();
		nodeStack12.pop();
		nodeStack12.pop();
		nodeStack12.printStack();
		nodeStack12.pop();
		nodeStack12.pop();
		nodeStack12.printStack();
		nodeStack12.pop();
		System.out.println(nodeStack12.isEmpty());
		
		System.out.println("-----nodeStack13");
		NodeStack13<Integer> nodeStack13 = new NodeStack13<Integer>();
		nodeStack13.push(1);
		nodeStack13.peek();
		nodeStack13.push(2);
		nodeStack13.push(4);
		nodeStack13.push(5);
		nodeStack13.push(3); 
		nodeStack13.printStack();
		nodeStack13.pop();
		nodeStack13.pop();
		nodeStack13.printStack();
		nodeStack13.pop();
		nodeStack13.pop();
		nodeStack13.printStack();
		nodeStack13.pop();
		nodeStack13.clear();
		System.out.println(nodeStack13.isEmpty());
		 
		System.out.println("-----nodeStack14");
		NodeStack14<Integer> nodeStack14 = new NodeStack14<Integer>();
		nodeStack14.push(1);
		nodeStack14.peek();
		nodeStack14.push(2);
		nodeStack14.push(4);
		nodeStack14.push(5);
		nodeStack14.push(3); 
		nodeStack14.printStack();
		nodeStack14.pop();
		nodeStack14.pop();
		nodeStack14.printStack();
		nodeStack14.pop();
		nodeStack14.pop();
		nodeStack14.printStack();
		nodeStack14.pop();
		nodeStack14.clear();
		System.out.println(nodeStack14.isEmpty());
		
		System.out.println("-----nodeStack15");
		NodeStack15<Integer> nodeStack15 = new NodeStack15<Integer>();
		nodeStack15.push(1);
		nodeStack15.peek();
		nodeStack15.push(2);
		nodeStack15.push(4);
		nodeStack15.push(5);
		nodeStack15.push(3); 
		nodeStack15.printStack();
		nodeStack15.pop();
		nodeStack15.pop();
		nodeStack15.printStack();
		nodeStack15.pop();
		nodeStack15.pop();
		nodeStack15.printStack();
		nodeStack15.pop();
		nodeStack15.clear();
		System.out.println(nodeStack15.isEmpty());
		
		System.out.println("-----nodeStack16");
		NodeStack16<Integer> nodeStack16 = new NodeStack16<Integer>();
		nodeStack16.push(1);
		nodeStack16.peek();
		nodeStack16.push(2);
		nodeStack16.push(4);
		nodeStack16.push(5);
		nodeStack16.push(3); 
		nodeStack16.printStack();
		nodeStack16.pop();
		nodeStack16.pop();
		nodeStack16.printStack();
		nodeStack16.pop();
		nodeStack16.pop();
		nodeStack16.printStack();
		nodeStack16.pop();
		nodeStack16.clear();
		System.out.println(nodeStack16.isEmpty());
		
		System.out.println("-----nodeStack17");
		NodeStack17<Integer> nodeStack17 = new NodeStack17<Integer>();
		nodeStack17.push(1);
		nodeStack17.peek();
		nodeStack17.push(2);
		nodeStack17.push(4);
		nodeStack17.push(5);
		nodeStack17.push(3); 
		nodeStack17.printStack();
		nodeStack17.pop();
		nodeStack17.pop();
		nodeStack17.printStack();
		nodeStack17.pop();
		nodeStack17.pop();
		nodeStack17.printStack();
		nodeStack17.pop();
		nodeStack17.clear();
		System.out.println(nodeStack17.isEmpty());
		
		System.out.println("-----nodeStack18");
		NodeStack18<Integer> nodeStack18 = new NodeStack18<Integer>();
		nodeStack18.push(1);
		nodeStack18.peek();
		nodeStack18.push(2);
		nodeStack18.push(4);
		nodeStack18.push(5);
		nodeStack18.push(3); 
		nodeStack18.printStack();
		nodeStack18.pop();
		nodeStack18.pop();
		nodeStack18.printStack();
		nodeStack18.pop();
		nodeStack18.pop();
		nodeStack18.printStack();
		nodeStack18.pop();
		//nodeStack18.peek();
		//nodeStack18.clear();
		
		System.out.println("-----nodeStack19");
		NodeStack19<Integer> nodeStack19 = new NodeStack19<Integer>();
		nodeStack19.push(1);
		nodeStack19.peek();
		nodeStack19.push(2);
		nodeStack19.push(4);
		nodeStack19.push(5);
		nodeStack19.push(3); 
		nodeStack19.printStack();
		nodeStack19.pop();
		nodeStack19.pop();
		nodeStack19.printStack();
		nodeStack19.pop();
		nodeStack19.pop();
		nodeStack19.printStack();
		nodeStack19.pop();
		
		System.out.println("-----nodeStack20");
		NodeStack20<Integer> nodeStack20 = new NodeStack20<Integer>();
		nodeStack20.push(1);
		nodeStack20.peek();
		nodeStack20.push(2);
		nodeStack20.push(4);
		nodeStack20.push(5);
		nodeStack20.push(3); 
		nodeStack20.printStack();
		nodeStack20.pop();
		nodeStack20.pop();
		nodeStack20.printStack();
		nodeStack20.pop();
		nodeStack20.pop();
		nodeStack20.printStack();
		nodeStack20.pop();
		
		System.out.println("-----nodeStack21");
		NodeStack21<Integer> nodeStack21 = new NodeStack21<Integer>();
		nodeStack21.push(1);
		nodeStack21.peek();
		nodeStack21.push(2);
		nodeStack21.push(4);
		nodeStack21.push(5);
		nodeStack21.push(3); 
		nodeStack21.printStack();
		nodeStack21.pop();
		nodeStack21.pop();
		nodeStack21.printStack();
		nodeStack21.pop();
		nodeStack21.pop();
		nodeStack21.printStack();
		nodeStack21.pop();
		
		System.out.println("-----nodeStack22");
		NodeStack22<Integer> nodeStack22 = new NodeStack22<Integer>();
		nodeStack22.push(1);
		nodeStack22.peek();
		nodeStack22.push(2);
		nodeStack22.push(4);
		nodeStack22.push(5);
		nodeStack22.push(3); 
		nodeStack22.printStack();
		nodeStack22.pop();
		nodeStack22.pop();
		nodeStack22.printStack();
		nodeStack22.pop();
		nodeStack22.pop();
		nodeStack22.printStack();
		nodeStack22.pop();
		
		System.out.println("-----nodeStack23");
		NodeStack23<Integer> nodeStack23 = new NodeStack23<Integer>();
		nodeStack23.push(1);
		nodeStack23.peek();
		nodeStack23.push(2);
		nodeStack23.push(4);
		nodeStack23.push(5);
		nodeStack23.push(3); 
		nodeStack23.printStack();
		nodeStack23.pop();
		nodeStack23.pop();
		nodeStack23.printStack();
		nodeStack23.pop();
		nodeStack23.pop();
		nodeStack23.printStack();
		nodeStack23.pop();
		
		System.out.println("-----nodeStack24");
		NodeStack24<Integer> nodeStack24 = new NodeStack24<Integer>();
		nodeStack24.push(1);
		nodeStack24.peek();
		nodeStack24.push(2);
		nodeStack24.push(4);
		nodeStack24.push(5);
		nodeStack24.push(3); 
		nodeStack24.printStack();
		nodeStack24.pop();
		nodeStack24.pop();
		nodeStack24.printStack();
		nodeStack24.pop();
		nodeStack24.pop();
		nodeStack24.printStack();
		nodeStack24.pop();
		
		System.out.println("-----nodeStack25");
		NodeStack25<Integer> nodeStack25 = new NodeStack25<Integer>();
		nodeStack25.push(1);
		nodeStack25.peek();
		nodeStack25.push(2);
		nodeStack25.push(4);
		nodeStack25.push(5);
		nodeStack25.push(3); 
		nodeStack25.printStack();
		nodeStack25.pop();
		nodeStack25.pop();
		nodeStack25.printStack();
		nodeStack25.pop();
		nodeStack25.pop();
		nodeStack25.printStack();
		nodeStack25.pop();
	}

}
